#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use SqlParserTest\Command\ParseCommand;
use Symfony\Component\Console\Application;

$application = new Application('parse');
$command = new ParseCommand();

$application->add($command);

$application->setDefaultCommand($command->getName(), true);
$application->run();

